#!/bin/bash -e

for cmd in pandoc wkhtmltopdf
do
  command -v "$cmd" > /dev/null || {
    sudo apt install "$cmd"
  }
done

if { [[ "$#" = 1 ]] && [[ "${1##*.}" -eq 'md' ]];}
then
  pandoc "$1" -o "${1%.*}.pdf" -f gfm \
         --pdf-engine=wkhtmltopdf \
         --highlight-style=pygments \
         --quiet
  echo "Created: ${1%.*}.pdf" >&2
else
  echo './md2pdf <markdown>' >&2
fi
